### ISSUE TITLE
A-Frame is imported as part of dist bundle

### ISSUE THREAD

**Issue by dsinni** [extraymond/aframe-mouse-dragndrop#2]
Hi! Digging the component. Well done.

That said, it looks like A-Frame is getting imported along with the component, which is resulting in a rather large distribution bundle.

Typically, A-Frame components do not include A-Frame in the dist, as it's up to the developer to either provide the CDN script or import it themselves as part of their project using the version they prefer. Importing more than once will result in conflicts and errors.

Just my $0.02. Keep up the good work and hope to see this change.

Looking forward to playing with this component a bit more.

Thanks.

**Comment by extraymond** [comment]
Thx for pointing that out! Just learning packaging npm modules. 
Will try to split that later.

**Comment by extraymond** [comment]
Fixed in the new release, bundle size should be much smaller.
